### ISSUE TITLE
add notice for debian users

### ISSUE THREAD

**Issue by GochoMugo** [mafintosh/benny-hill#1]
You could add such a notice for users running Debian (or Ubuntu-based) distros:

To install the `play` command, with mp3 support, run:

``` bash
$ sudo apt-get install sox libsox-fmt-mp3
```

Otherwise,

Great, little command :smile: :+1:

**Comment by ungoldman** [comment]
don't have play on my system so I got an `Error: spawn play ENOENT`

could fallback to afplay but probably not worth the trouble. thanks for the laffs! 😆

**Comment by mafintosh** [comment]
@ungoldman now falls back to afplay

**Comment by mciparelli** [comment]
@mafintosh didn't have `play` installed, I got such Error, but it still ran `npm i`. No fun, bug :D

**Comment by mafintosh** [comment]
@mciparelli which platform? should always work on osx now

**Comment by mafintosh** [comment]
i've added this notice to the readme btw

**Comment by mciparelli** [comment]
debian jessie. Didn't stop `npm i` from happening after outputting given error.

**Comment by mciparelli** [comment]
And actually it may not be a bug at all. You might not want to handle the case when the user doesn't have `play` installed or you might even want the command to still run if he doesn't have `play` installed and that's fine too
