### ISSUE TITLE
Playback stops during lengthy processes

### ISSUE THREAD

**Issue by Michcioperz** [mafintosh/benny-hill#8]
I tried this on short processes first such as the ones mentioned in the README, but then I went ahead and just did `benny-hilll yaourt -Sayu` to update my whole system, and the music stopped after a few minutes.

**Comment by mafintosh** [comment]
CRITICAL BUG! Fixed in 1.1.1

**Comment by mafintosh** [comment]
also simply `benny-hill` will now keep playing forever
